# Default values for exemplocronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

job:
  name: meu-cronjob
  image:
    repository: cronjob
    tag: stable
    imagePullPolicy: IfNotPresent
  schedule: "*/1 * * * *"
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  nodeSelector: {}
  tolerations: []
  affinity: {}
