# Default values for chart-cronjob.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

job:
  name: hello-cronjob
  image:
    repository: cronjob
    tag: stable1
    imagePullPolicy: IfNotPresent
  schedule: "*/1 * * * *"
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}